// Code generated by Slice Machine. DO NOT EDIT.

import Columns from './Columns';
import Image from './Image';
import Images from './Images';

export {
	Columns,
	Image,
	Images,
};

export const components = {
	columns: Columns,
	image: Image,
	images: Images,
};
