// Code generated by Slice Machine. DO NOT EDIT.

import Columns from './Columns';
import Image from './Image';
import Images from './Images';
import ThemeMenu from './ThemeMenu';

export {
	Columns,
	Image,
	Images,
	ThemeMenu,
};

export const components = {
	columns: Columns,
	image: Image,
	images: Images,
	theme_menu: ThemeMenu,
};
